config/routes.rb
Workroom::Application.routes.draw do
  get "users/new"
  root 'static_pages#home'
  get "static_pages/home"
  get "static_pages/resume"

  scope module: :web do
    namespace :admin do
      root to: "welcome#index"
      resources :categories
      resources :links
      resources :sections
      resources :posts
      resources :users
      resources :sessions, only: [:new, :create, :destroy]
      match '/signin',  to: 'sessions#new',         via: 'get'
      match '/signout', to: 'sessions#destroy',     via: 'delete'
    end

    resources :category, only: [] do      
      resources :posts, only: [:index]
      resources :links, only: [:index], action: "index_category_links"
    end

    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, only: [:index, :show]
    resources :links, only: [:index]
  end

  

end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :categories, dependent: :destroy

  before_save { |section| section.name = name.downcase }
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }

  def Section.create_default_sections
    unless Section.find_by_name("links")
      Section.create(name: "links")
    end

    unless Section.find_by_name("posts")
      Section.create(name: "posts")
    end
  end
end

app/controllers/web/admin/sections_controller.rb
class Web::Admin::SectionsController < Web::Admin::AdminApplicationController
  def index
    @q = Section.ransack params[:q]
    @sections = @q.result.order(sort_string).page(params[:page])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:success] = "Раздел создан"
      redirect_to admin_sections_url
    else
      render 'new'
    end
  end

  def destroy
    Section.find(params[:id]).destroy
    flash[:success] = "Раздел удален"
    redirect_to admin_sections_url
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(section_params)
      flash[:success] = "Раздел обновлён"
      redirect_to admin_sections_url
    else
      render 'edit'
    end
  end

  private
    def section_params
      params.require(:section).permit(:name)
    end
end

app/helpers/web/admin/sections_helper.rb
module Web::Admin::SectionsHelper
end

app/views/web/admin/sections/_form.html.erb
<%= simple_form_for @section, url: admin_section_path(@section),
  wrapper_mappings: {
    check_boxes: :vertical_radio_and_checkboxes,
    boolean: :vertical_boolean
  } do |f| %>
  <%= f.error_notification %>
  
  <%= render 'shared/error_messages', object: f.object %>
  
  <%= f.input :name, label: "Название" %>

  <%= f.submit submit_title, class: "btn btn-large btn-primary"  %> 
<% end %>

app/views/web/admin/sections/edit.html.erb
<% provide(:title, 'Admin section update') %>
<div class="thema-text">Обновление раздела</div>

<div class="row">
  <div class="col-md-12">
    <%= render 'form', submit_title: "Сохранить изменения" %>
  </div>
</div>

app/views/web/admin/sections/index.html.erb
<% provide(:title, 'Admin section') %>
<div class="thema-text">Администрирование разделов</div>

<div class="button_new_record_db">
  <%= link_to 'Новый раздел...', new_admin_section_path, :class => 'btn btn-primary' %>
</div>
<table class="table table-bordered">
	<thead>
		<tr>
			<th><%= sort_link @q, :id %></th>
      <th><%= sort_link @q, :created_at %></th>
			<th><%= sort_link @q, :name %></th>
			<th></th>
		</tr>

		<tbody>
      <% @sections.each do |item| %>
        <tr>
        	<td><%= item.id %></td>
          <td><%= item.created_at %></td>
        	<td><%= item.name %></td>
        	<td>
            <div class="btn-group">
              <%= link_to edit_admin_section_path(item), class: 'btn btn-success btn-sm' do %>
                Изм.
              <% end %>

              <%= link_to admin_section_path(item), method: :delete, data: { confirm: "Вы уверены?" }, class: 'btn btn-danger btn-sm' do %>
                Удал.
              <% end %>
            </div>
        	</td>
        </tr>
      <% end %>
    </tbody>
	</thead>
</table>

<%= will_paginate @sections %>

app/views/web/admin/sections/new.html.erb
<% provide(:title, 'Admin section create') %>
<div class="thema-text">Создание нового раздела</div>

<div class="row">
  <div class="col-md-12">
    <%= render 'form', submit_title: "Создать раздел" %>
  </div>
</div>