config/routes.rb
Workroom::Application.routes.draw do
  get "users/new"
  root 'static_pages#home'
  get "static_pages/home"
  get "static_pages/resume"

  scope module: :web do
    namespace :admin do
      root to: "welcome#index"
      resources :categories
      resources :links
      resources :sections
      resources :posts
      resources :users
      resources :sessions, only: [:new, :create, :destroy]
      match '/signin',  to: 'sessions#new',         via: 'get'
      match '/signout', to: 'sessions#destroy',     via: 'delete'
    end

    resources :category, only: [] do      
      resources :posts, only: [:index]
      resources :links, only: [:index], action: "index_category_links"
    end

    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, only: [:index, :show]
    resources :links, only: [:index]
  end

  

end

app/controllers/web/admin/welcome_controller.rb
class Web::Admin::WelcomeController < Web::Admin::AdminApplicationController
  def index
  end
end

app/helpers/web/admin/welcome_helper.rb
module Web::Admin::WelcomeHelper
end

app/views/web/admin/welcome/index.html.erb
<% provide(:title, 'Admin') %>
<div class="thema-text">Административная панель</div>

<ul>
  <li><%= link_to "Разделы", admin_sections_path %></li>
  <li><%= link_to "Категории", admin_categories_path %></li>
  <li><%= link_to "Ссылки", admin_links_path %></li>
  <li><%= link_to "Заметки", admin_posts_path %></li>
  <li><%= link_to "Пользователи", admin_users_path %></li>
</ul>

<p>
	<b>Подсказка по CSS оформлению текста</b>
	<div class="color-green"> class="color-green" - зелёный цвет</div>
	<div class="color-red"> class="color-red" - красный цвет</div>
	<div class="color-yellow"> class="color-yellow" - жёлтый цвет</div>
	<div class="color-blue"> class="color-blue" - синий цвет</div>
  </br>
  <div>class="center" - центрирование</div>
  <div>class="fix-position" - фиксированная позиция</div>
  <div>class="thema-text" - название темы (font: 20pt sans-serif; margin: 5px 5px 25px 0px;)</div>

</p>