config/routes.rb
Workroom::Application.routes.draw do
  get "users/new"
  root 'static_pages#home'
  get "static_pages/home"
  get "static_pages/resume"

  scope module: :web do
    namespace :admin do
      root to: "welcome#index"
      resources :categories
      resources :links
      resources :sections
      resources :posts
      resources :users
      resources :sessions, only: [:new, :create, :destroy]
      match '/signin',  to: 'sessions#new',         via: 'get'
      match '/signout', to: 'sessions#destroy',     via: 'delete'
    end

    resources :category, only: [] do      
      resources :posts, only: [:index]
      resources :links, only: [:index], action: "index_category_links"
    end

    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, only: [:index, :show]
    resources :links, only: [:index]
  end

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category

  #accepts_nested_attributes_for :tag_list
  acts_as_taggable

  validates :title, :category_id, :content, presence: true
  validates :title, uniqueness: { scope: :category_id, case_sensitive: false }

  #scope :published_filter, ->(pub) { where(published: pub) }
  #scope :title_like_filter, ->(title) { where("title like ?", "%#{title}%") }
  #scope :category_filter, ->(category_id) { where(category_id: category_id) }

  def self.categories
    section = Section.find_by_name("posts")
    Category.where(section_id: section)
  end

  def self.search(posts_params)
    posts = Post.all
    posts = posts.where(published: true)
    posts = posts.where(category_id: posts_params[:category_id]) if posts_params.has_key?(:category_id)
    posts = posts.where("lower(title) LIKE lower(?)", "%" + posts_params[:search] + "%") if posts_params.has_key?(:search)
    posts
  end

  def self.filter(params)
    posts = Post.all
    posts = posts.where("lower(title) LIKE lower(?)", "%" + params[:sSearch_2] + "%") if params.has_key?(:sSearch_2) && !params[:sSearch_2].empty?
    posts = posts.order("#{sort_column(params[:iSortCol_0].to_i)} #{params[:sSortDir_0]}")
    
    if params.has_key?(:sSearch_3) && !params[:sSearch_3].empty?
      categoryIds = params[:sSearch_3].split(',')
      categoryIds.each do |categoryId|
        posts = posts.where("category_id = ?", categoryId)
      end
    end

    if params.has_key?(:sSearch_4) && !params[:sSearch_4].empty?
      publisheds = params[:sSearch_4].split(',')
      publisheds.each do |pub|
        posts = posts.where("published = ?", pub[0]) if !pub.empty?
      end
    end    

    pg = getPage(params)
    pp = getPerPage(params)
    posts = posts.page(pg).per_page(pp)
    #posts = posts.page(2).per_page(10)
    #posts = posts.paginate(:page => params[:page], :per_page => 30)

    puts "AAAA LLLLL RRRRR " << pg.to_s << " " << pp.to_s << " | " << params[:iDisplayStart].to_s << " " << params[:iDisplayLength].to_s

    #posts = posts.offset(params[:iDisplayStart]).limit(params[:iDisplayLength])
    posts
  end

  #def self.filter2(params)
  #  posts = where(nil) #creates an anonymous scope
  #end

  
    def self.getPage(params)
      params[:iDisplayStart].to_i/getPerPage(params) + 1
    end

    def self.getPerPage(params)
      params[:iDisplayLength].to_i > 0 ? params[:iDisplayLength].to_i : 10
    end
  
  private
    def self.sort_column(number_column)
      columns = %w[id created_at title category_id published] 
      columns[number_column]
    end

    #def self.sort_direction()
    #  params[:sSortDir_0] == "desc" ? "desc" : "asc"
    #end
end

app/controllers/web/admin/posts_controller.rb
class Web::Admin::PostsController < Web::Admin::AdminApplicationController
  def index
    #@q = Post.ransack params[:q]
    #@posts = @q.result.order(sort_string).page(params[:page])
    respond_to do |format|
      format.html do
        @categories = Category.all
      end
      format.json do
        render json: PostDatatable.new(view_context)
      end
    end
  end

  def new
    @post = Post.new
    @categories_for_posts = Post.categories
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Заметка создана"
      redirect_to admin_posts_url
    else
      render 'new'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Заметка удалена"
    redirect_to admin_posts_url
  end

  def edit
    @post = Post.find(params[:id])
    @categories_for_posts = Post.categories
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Заметка обновлена"
      redirect_to admin_posts_url
    else
      render 'edit'
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :preview, :category_id, :published, :tag_list)
    end

end

app/controllers/web/posts_controller.rb
class Web::PostsController < ApplicationController
  include Publishable

  def index
    if (params[:tag])
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.search(posts_params)
    end
    @q = @posts.ransack params[:q]
    @posts = @q.result.order('created_at DESC').page(params[:page])
    @categories = Post.categories    
  end

  def show
    @categories = Post.categories
    @post = Post.find(params[:id])
    if published_content?(@post)
      @post
    else
      not_found
    end
  end

  private
    def posts_params
      params.permit(:category_id, :search, :tag)
    end
end

app/helpers/web/admin/posts_helper.rb
module Web::Admin::PostsHelper
end

app/helpers/web/posts_helper.rb
module Web::PostsHelper
end

app/views/web/posts/_posts_list.html.erb
                  <% if posts.count == 0 %>
                    <div class="center">
                      <h2>Ничего не найдено</h2>
                    </div>
                  <% else%>

                    <% posts.each do |post| %>
                      <div class="blog-post">
                        <!--<img alt="" src="upload/blog5.jpg">-->
                        <div class="postblog-content">
                          
                          <!--<ul class="post-tags">
                            <li>
                              <p>premiumlayers</p>
                              <span><i class="fa fa-user"></i></span>
                            </li>
                            <li>
                              <p>138 likes</p>
                              <span><i class="fa fa-heart"></i></span>
                            </li>
                            <li>
                              <p>14 February, 2014</p>
                              <span><i class="fa fa-calendar"></i></span>
                            </li>
                            <li>
                              <p><a href="#">4 Comments</a></p>
                              <span><i class="fa fa-comment"></i></span>
                            </li>
                          </ul>-->

                          <div class="blog-content">
                            <h2><%= link_to post.title, post_path(post) %></h2>
                            <p>
                              <%if (post.preview == nil) || (post.preview.empty?) %>
                                <div><%= summary_for_html_text(post.content) %></div>
                              <%else%>
                                <div><%= post.preview.html_safe %></div>
                              <%end%>
                              
                              <div>
                                Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
                              </div>

                              <div>
                                </br>
                                <span class="color-green">Категория: </span>
                                <%= link_to post.category.name, category_posts_path(post.category) %>
                              </div>
                            </p>
                            <%= link_to "Читать польностью", post_path(post), class: "read-more" %>
                          </div>
                        </div>
                      </div>
                    <% end %>

                  <% end %>

app/views/web/posts/_search_post.html.erb
<div class="search-widget widget">
	<%= form_tag posts_path, :method => 'get', enforce_utf8: false do %>
		<%= text_field_tag 'search', nil, placeholder: 'Search here...', id: "search-box", type: "search" %>
		<button type="submit">
			<i class="fa fa-search"></i>
		</button>
	<% end %>
</div>

app/views/web/posts/_tags_list.html.erb
<div class="widget tags-widget">
	<h2>Tags</h2>
	<ul class="tags-list">
		<!--
		<li><a href="#">web design</a></li>
		<li><a href="#">logo</a></li>
		<li><a href="#">php</a></li>
		<li><a href="#">ecommerce</a></li>
		<li><a href="#">development</a></li>
		<li><a href="#">graphic</a></li>-->
		<% tag_cloud Post.tag_counts, %w[small-tag middle-tag large-tag] do |tag, css_class| %>
		  <li><%= link_to tag.name, tag_path(tag.name), class: css_class %></li>
		<% end %>
	</ul>
</div>

app/views/web/posts/index.html.erb
		<div id="content">
			<div class="inner-content">
				<div class="blog-page">
					<div class="container">
						<div class="row">
							<div class="col-md-9">
								<div class="blog-box">
									<%= render 'web/posts/posts_list', posts: @posts %>
									<%= will_paginate @posts %>
								</div>
							</div>

							<div class="col-md-3">
								<div class="sidebar">

									<%= render 'search_post' %>

									<%= render 'web/shared/fixed_list_categories', categories: @categories, path_creator: method(:category_posts_path) %>
									
									<%= render 'tags_list' %>

									<!--<div class="widget archives-list-widget">
										<h2>Archives</h2>
										<ul class="doing-list">
											<li><a href="#">February 2014 <span>(35)</span></a></li>
											<li><a href="#">Jannuary 2014 <span>(12)</span></a></li>
											<li><a href="#">December 2013 <span>(46)</span></a></li>
										</ul>
									</div>-->
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

app/views/web/posts/show.html.erb
		<div id="content">
			<div class="inner-content">
				<div class="blog-page">
					<div class="container">
						<div class="row">
							<div class="col-md-9">
								<div class="blog-box">

									<div class="blog-post single-post">
										<!--<img alt="" src="upload/blog5.jpg">-->
										<div class="postblog-content">											
											<div class="blog-content">
												<h2><%= @post.title %></h2>
												<%= @post.content.html_safe %>
												<p>

												<div>
                          Tags: <%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
                        </div>

												<div>
													<span class="color-green">Категория: </span>
												  <%= link_to "#{@post.category.name}", posts_path(posts: {category_id: @post.category} ) %>
												</div>
											  </p>
											</div>
											<ul class="post-tags">
												<!--<li>
													<p>138 likes</p>
													<span><i class="fa fa-heart"></i></span>
												</li>-->
												<li>
													<p>14 February, 2014</p>
													<span><i class="fa fa-calendar"></i></span>
												</li>
												<!--<li>
													<p><a href="#">4 Comments</a></p>
													<span><i class="fa fa-comment"></i></span>
												</li>-->
											</ul>
										</div>
									</div>
									
									<!--<div class="about-autor">
										<h2>About the author</h2>
										
										<ul class="nav nav-tabs" id="myTab2">
											<li class="active"><a href="#biography" data-toggle="tab"><i class="fa fa-user"></i> <span>Biography</span></a></li>
											<li><a href="#facebook" data-toggle="tab"><i class="fa fa-facebook"></i> <span>Facebook</span></a></li>
											<li><a href="#twitter" data-toggle="tab"><i class="fa fa-twitter"></i> <span>Twitter</span></a></li>
											<li><a href="#google-plus" data-toggle="tab"><i class="fa fa-google-plus"></i> <span>Google+</span></a></li>
											<li><a href="#linkedin" data-toggle="tab"><i class="fa fa-linkedin"></i> <span>Linkedin</span></a></li>
										</ul>

										<div class="tab-content">
											<div class="tab-pane active" id="biography">
												<img alt="" src="upload/autor.jpg">
												<p>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  Lorem Ipsum.</p>
												<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris</p>
											</div>
											<div class="tab-pane" id="facebook">
												<p>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  Lorem Ipsum.</p>
												<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris</p>
											</div>
											<div class="tab-pane" id="twitter">
												<img alt="" src="upload/autor.jpg">
												<p>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  Lorem Ipsum.</p>
												<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris</p>

											</div>
											<div class="tab-pane" id="google-plus">
												<img alt="" src="upload/autor.jpg">
												<p>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  Lorem Ipsum.</p>
												<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris</p>
												<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris</p>

											</div>
											<div class="tab-pane" id="linkedin">
												<p>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  Lorem Ipsum.</p>
												<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris</p>
												<p>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  Lorem Ipsum.</p>
												<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris</p>

											</div>
										</div>
									</div>-->

									<!--<div class="comment-section">
										<h2>7 Comments</h2>

										<ul class="comment-tree">
											<li>
												<div class="comment-box">
													<img alt="" src="upload/avatar1.jpg">
													<div class="comment-content">
														<h6>ShaneFreer <span>/ 4 minutes ago</span></h6>
														<p>great post brainartworks</p>
													</div>
												</div>
												<ul class="depth">
													<li>
														<div class="comment-box">
															<img alt="" src="upload/avatar2.jpg">
															<div class="comment-content">
																<h6>Collis Ta'eed <span>/ 12 minutes ago</span></h6>
																<p>yeah i  really like it too, very useful!</p>
															</div>
														</div>
														<ul class="depth">
															<li>
																<div class="comment-box">
																	<img alt="" src="upload/avatar3.jpg">
																	<div class="comment-content">
																		<h6>Jremick <span>/ 20 minutes ago</span></h6>
																		<p>i found this post very useful too, the comment form works just perfect, keep it up guys :)</p>
																	</div>
																</div>
																<ul class="depth">
																	<li>
																		<div class="comment-box">
																			<img alt="" src="upload/avatar4.jpg">
																			<div class="comment-content">
																				<h6>joshjanssen <span>/ 36 minutes ago</span></h6>
																				<p>yep, especially when it comes to comment testing</p>
																			</div>
																		</div>
																	</li>
																</ul>
															</li>

															<li>
																<div class="comment-box">
																	<img alt="" src="upload/avatar5.jpg">
																	<div class="comment-content">
																		<h6>Stewboon <span>/ 40 minutes ago</span></h6>
																		<p>nice job!</p>
																	</div>
																</div>
															</li>
														</ul>
													</li>

													<li>
														<div class="comment-box">
															<img alt="" src="upload/avatar6.jpg">
															<div class="comment-content">
																<h6>bensmithett <span>/ 42 minutes ago</span></h6>
																<p>couldn’t be better :D</p>
															</div>
														</div>
													</li>
												</ul>
											</li>

											<li>
												<div class="comment-box">
													<img alt="" src="upload/avatar7.jpg">
													<div class="comment-content">
														<h6>justinfrench <span>/ 48 minutes ago</span></h6>
														<p>looks very promising</p>
													</div>
												</div>
											</li>
										</ul>
									</div>
									<form class="comment-form">
										<h2>Leave a comment</h2>
										<div class="text-fields">
											<div class="float-input">
												<input name="name" id="name" type="text" placeholder="Name">
												<span><i class="fa fa-user"></i></span>
											</div>
											<div class="float-input">
												<input name="mail" id="mail" type="text" placeholder="e-mail">
												<span><i class="fa fa-envelope-o"></i></span>
											</div>
											<div class="float-input">
												<input name="website" id="website" type="text" placeholder="website">
												<span><i class="fa fa-link"></i></span>
											</div>
										</div>

										<div class="submit-area">
											<textarea name="comment" id="comment" placeholder="Message"></textarea>
											<input type="submit" id="submit_contact" class="main-button" value="Send Now">
										</div>
									</form>-->
								</div>
							</div>

							<div class="col-md-3">
								<div class="sidebar">

									<!--<div class="search-widget widget">
										<form>
											<input type="search" placeholder="Search here..."/>
											<button type="submit">
												<i class="fa fa-search"></i>
											</button>
										</form>
									</div>-->

									<%= render 'search_post' %>

									<%= render 'web/shared/fixed_list_categories', categories: @categories, path_creator: method(:category_posts_path) %>

									<!--<div class="widget tags-widget">
										<h2>Tags</h2>
										<ul class="tags-list">
											<li><a href="#">web design</a></li>
											<li><a href="#">logo</a></li>
											<li><a href="#">php</a></li>
											<li><a href="#">ecommerce</a></li>
											<li><a href="#">development</a></li>
											<li><a href="#">graphic</a></li>
										</ul>
									</div>

									<div class="widget archives-list-widget">
										<h2>Archives</h2>
										<ul class="doing-list">
											<li><a href="#">February 2014 <span>(35)</span></a></li>
											<li><a href="#">Jannuary 2014 <span>(12)</span></a></li>
											<li><a href="#">December 2013 <span>(46)</span></a></li>
										</ul>
									</div>-->

								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>