config/routes.rb
Workroom::Application.routes.draw do
  get "users/new"
  root 'static_pages#home'
  get "static_pages/home"
  get "static_pages/resume"

  scope module: :web do
    namespace :admin do
      root to: "welcome#index"
      resources :categories
      resources :links
      resources :sections
      resources :posts
      resources :users
      resources :sessions, only: [:new, :create, :destroy]
      match '/signin',  to: 'sessions#new',         via: 'get'
      match '/signout', to: 'sessions#destroy',     via: 'delete'
    end

    resources :category, only: [] do      
      resources :posts, only: [:index]
      resources :links, only: [:index], action: "index_category_links"
    end

    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, only: [:index, :show]
    resources :links, only: [:index]
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  before_create :create_remember_token

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }
  # validates :password_confirmation, presence: true


  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def User.create_first_admin
    first_admin = User.new(name: "admin", email: "admin@admin.ru", password: "admin", password_confirmation: "admin")
    first_admin.save(validate: false)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end  
end

app/controllers/web/admin/users_controller.rb
class Web::Admin::UsersController < Web::Admin::AdminApplicationController
  def index
    @q = User.ransack params[:q]
    @users = @q.result.order(sort_string).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Пользователь создан"
      redirect_to admin_users_url
    else
      render 'new'
    end
  end

  def destroy
    user = User.find(params[:id])
    if (user == current_user)
      flash[:danger] = "Вы не можете удалить собственный акаунт"
    else
      user.destroy
      flash[:success] = "Пользователь удален"
    end
    redirect_to admin_users_url
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Информация о пользователе обновлена"
      redirect_to admin_users_url
    else
      render 'edit'
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end


end

app/helpers/web/admin/users_helper.rb
module Web::Admin::UsersHelper
end

app/views/web/admin/users/_form.html.erb
<%= simple_form_for @user, url: admin_user_path(@user),
  wrapper_mappings: {
    check_boxes: :vertical_radio_and_checkboxes,
    boolean: :vertical_boolean
  } do |f| %>
  <%= f.error_notification %>
  
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.input :name, label: 'Имя' %>
  <%= f.input :email, label: 'e-mail' %>
  <%= f.input :password, label: 'Пароль' %>
  <%= f.input :password_confirmation, label: 'Подтверждение пароля' %>

  <%= f.submit submit_title, class: "btn btn-large btn-primary"  %> 
<% end %>

app/views/web/admin/users/edit.html.erb
<% provide(:title, 'Admin user update') %>
<div class="thema-text">Обновление пользователя</div>

<div class="row">
  <div class="col-md-12">
    <%= render 'form', submit_title: "Сохранить изменения" %>
  </div>
</div>

app/views/web/admin/users/index.html.erb
<% provide(:title, 'Admin user') %>
<div class="thema-text">Администрирование пользователей</div>

<div class="button_new_record_db">
  <%= link_to 'Новый пользователь...', new_admin_user_path, :class => 'btn btn-primary' %>
</div>
<table class="table table-bordered">
	<thead>
		<tr>
			<th><%= sort_link @q, :id %></th>
      <th><%= sort_link @q, :created_at %></th>
			<th><%= sort_link @q, :name %></th>
      <th><%= sort_link @q, :email %></th>
			<th></th>
		</tr>
		<tbody>
      <% @users.each do |item| %>
        <tr>
        	<td><%= item.id %></td>
          <td><%= item.created_at %></td>
        	<td><%= item.name %></td>
          <td><%= item.email %></td>
          <td>
            <div class="btn-group">
              <%= link_to edit_admin_user_path(item), class: 'btn btn-success btn-sm' do %>
                Изм.
              <% end %>

              <%= link_to admin_user_path(item), method: :delete, data: { confirm: "Вы уверены?" }, class: 'btn btn-danger btn-sm' do %>
                Удал.
              <% end %>
            </div>
        	</td>
        </tr>
      <% end %>
    </tbody>
	</thead>
</table>

<%= will_paginate @users %>

app/views/web/admin/users/new.html.erb
<% provide(:title, 'Admin user create') %>
<div class="thema-text">Создание нового пользователя</div>

<div class="row">
  <div class="col-md-12">
    <%= render 'form', submit_title: "Создать пользователя" %>
  </div>
</div>